# Site settings
title: Boust Bioinformatics
email: cboustred@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Diary, blog, aide memoire for bioinformatics work
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cboustred.github.io" # the base hostname & protocol for your site
twitter_username: cboustred
github_username:  cboustred

# Build settings
markdown: kramdown
